name: Deploy to Hostinger via FTP

on:
  push:
    branches:
      - main # Change this if your main branch is called 'master'

jobs:
  web-deploy:
    name: Deploy to Hostinger
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
    
     # ADD THIS NEW STEP HERE:
    - name: Create Cache Directory
      run: mkdir -p bootstrap/cache
        
    - name: Install Composer Dependencies
      run: |
        cp .env.example .env
        composer install --no-dev --optimize-autoloader

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Build Frontend
      run: |
        sed -i 's|APP_URL=http://localhost|APP_URL=https://darkred-locust-486842.hostingersite.com|g' .env
        npm install
        npm run build

    - name: Sync files to Hostinger
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/ # Make sure this matches your Hostinger folder!
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .env